### ISSUE TITLE
Can't render custom elements

### ISSUE THREAD

**Issue by mnquintana** [atom/etch#30]
It looks like `virtual-dom` doesn't play nicely with custom elements 😞 

### Steps to Reproduce

1. Create a custom element (e.g. `atom-text-editor`)
1. Try to render that custom element in JSX
1. `etch` will throw an error:
```
Error: Failed to execute 'createElement' on 'Document': The tag name provided ('[') is not a valid name.
    at Error (native)
    at createElement (/Users/machistequintana/github/command-palette/node_modules/virtual-dom/vdom/create-element.js:30:13)
    at createElement (/Users/machistequintana/github/command-palette/node_modules/virtual-dom/vdom/create-element.js:39:25)
    at Object.initialize (/Users/machistequintana/github/command-palette/node_modules/etch/dist/component-helpers.js:68:64)
```

**Comment by mnquintana** [comment]
Just kidding, this was totally my fault 🙈
